name: Branch Deploy

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Branch to deploy'
        required: true
        type: string
      neon-username:
        description: 'Neon username'
        required: true
        type: string
        default: neondb_owner

jobs:
  setup-database:
    runs-on: ubuntu-latest
    steps:
      - name: Create Neon Database Branch
        uses: neondatabase/create-branch-action@v5
        id: create-branch
        with:
          project_id: ${{ secrets.NEON_BRANCH_PROJECT_ID }}
          branch_name: ${{ github.event.inputs.branch-name }}
          database: neondb
          username: ${{ github.event.inputs.neon-username }}
          prisma: true
          api_key: ${{ secrets.NEON_API_KEY }}
      - name: Echo Database URL
        run: echo "Database URL ${{ steps.create-branch.outputs.db_url }}"
      - name: Echo Host
        run: echo "Host ${{ steps.create-branch.outputs.host }}"
      - name: Echo Branch ID
        run: echo "Branch ID ${{ steps.create-branch.outputs.branch_id }}"
  

  setup-heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Heroku CLI
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "dealstack-be-test-deploy"  # Replace with your Heroku app's name
          heroku_email: "andrew.ho@dealstack.io"  # Replace with your Heroku account email
          usedocker: true  # Optional: Set this to true if you are deploying a Docker container

  run-heroku:
    needs: setup-heroku
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Heroku
        run: |
          heroku container:login
          heroku container:push web -a dealstack-be-test-deploy
          heroku container:release web -a dealstack-be-test-deploy

