name: Branch Deploy

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Branch to deploy'
        required: true
        type: string
        default: 'branch-review-2'
      neon-username:
        description: 'Neon username'
        required: true
        type: string
        default: db_user_for_url
      

jobs:
  setup-database:
    runs-on: ubuntu-latest
    steps:
      - name: Create Neon Database Branch
        uses: neondatabase/create-branch-action@v5
        id: create-branch
        with:
          project_id: ${{ secrets.NEON_BRANCH_PROJECT_ID }}
          branch_name: ${{ github.event.inputs.branch-name }}
          database: neondb
          username: ${{ github.event.inputs.neon-username }}
          prisma: true
          api_key: ${{ secrets.NEON_API_KEY }}
      
      - name: Echo Database URL
        run: echo "Database URL ${{ steps.create-branch.outputs.db_url }}"
      
      - name: Echo Host
        run: echo "Host ${{ steps.create-branch.outputs.host }}"
      
      - name: Echo Branch ID
        run: echo "Branch ID ${{ steps.create-branch.outputs.branch_id }}"
