name: Test Deploy
on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Branch to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hello
        run: echo "Hello"

      - name: Set Deployment Environment
        id: set-env
        run: echo "environment=production" >> $GITHUB_ENV

      - name: Approval for Production Deployment
        if: ${{ env.environment == 'production' }}
        env: 
          name: production
        run: echo "Waiting for manual approval to deploy to Production"
        # This step will pause the workflow until manual approval is granted in the "production" environment

      - name: Deploy to Production
        if: ${{ env.environment == 'production' }}
        run: |
          echo "Deploying to Production"
          # Add production deployment commands here

      - name: Deploy to Staging
        if: ${{ env.environment != 'production' }}
        run: |
          echo "Deploying to Staging"
          # Add staging deployment commands here

      - name: Echo Finished
        run: echo "Finished"
